package lofod.products.ui.theme

import androidx.compose.ui.graphics.Color

// Neutral MD3 fallback (used when dynamic color is unavailable).
val PrimaryLight = Color(0xFF386A20)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFB7F397)
val OnPrimaryContainerLight = Color(0xFF042100)
val SecondaryLight = Color(0xFF55624C)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFD8E7CB)
val OnSecondaryContainerLight = Color(0xFF131F0D)
val TertiaryLight = Color(0xFF386667)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFBBEBEC)
val OnTertiaryContainerLight = Color(0xFF002021)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410002)
val BackgroundLight = Color(0xFFF7FBF1)
val OnBackgroundLight = Color(0xFF191D17)
val SurfaceLight = Color(0xFFF7FBF1)
val OnSurfaceLight = Color(0xFF191D17)
val SurfaceVariantLight = Color(0xFFE0E4D7)
val OnSurfaceVariantLight = Color(0xFF43483E)
val OutlineLight = Color(0xFF74796D)

val PrimaryDark = Color(0xFF9CD67E)
val OnPrimaryDark = Color(0xFF123800)
val PrimaryContainerDark = Color(0xFF215107)
val OnPrimaryContainerDark = Color(0xFFB7F397)
val SecondaryDark = Color(0xFFBCCBB0)
val OnSecondaryDark = Color(0xFF273421)
val SecondaryContainerDark = Color(0xFF3D4B36)
val OnSecondaryContainerDark = Color(0xFFD8E7CB)
val TertiaryDark = Color(0xFFA0CFD0)
val OnTertiaryDark = Color(0xFF003738)
val TertiaryContainerDark = Color(0xFF1E4E4F)
val OnTertiaryContainerDark = Color(0xFFBBEBEC)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)
val BackgroundDark = Color(0xFF10140F)
val OnBackgroundDark = Color(0xFFE0E4D7)
val SurfaceDark = Color(0xFF10140F)
val OnSurfaceDark = Color(0xFFE0E4D7)
val SurfaceVariantDark = Color(0xFF43483E)
val OnSurfaceVariantDark = Color(0xFFC3C8BB)
val OutlineDark = Color(0xFF8D9286)
